// Auth types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Restaurant types
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_FAILURE = 'FETCH_RESTAURANTS_FAILURE';
export const FETCH_RESTAURANT_DETAILS_SUCCESS = 'FETCH_RESTAURANT_DETAILS_SUCCESS';
export const FETCH_RESTAURANT_DETAILS_FAILURE = 'FETCH_RESTAURANT_DETAILS_FAILURE';
export const UPDATE_RESTAURANT_PROFILE = 'UPDATE_RESTAURANT_PROFILE';
export const FETCH_RESTAURANT_DISHES_SUCCESS = 'FETCH_RESTAURANT_DISHES_SUCCESS';
export const FETCH_RESTAURANT_DISHES_FAILURE = 'FETCH_RESTAURANT_DISHES_FAILURE';
export const ADD_DISH_SUCCESS = 'ADD_DISH_SUCCESS';
export const ADD_DISH_FAILURE = 'ADD_DISH_FAILURE';
export const UPDATE_DISH_SUCCESS = 'UPDATE_DISH_SUCCESS';
export const UPDATE_DISH_FAILURE = 'UPDATE_DISH_FAILURE';

// Order types
export const ORDER_CREATED = 'ORDER_CREATED';
export const ORDER_UPDATED = 'ORDER_UPDATED';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
export const FETCH_ORDER_DETAILS_SUCCESS = 'FETCH_ORDER_DETAILS_SUCCESS';
export const FETCH_ORDER_DETAILS_FAILURE = 'FETCH_ORDER_DETAILS_FAILURE';
